export const BOOK_LIST = [
  {
    image: "/book-covers/lazarus-rising.jpg",
    title: "Lazarus Rising",
    author: "Caldwell, Joseph",
    mediaType: "book",
    holds: 0,
    copies: 4,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
  {
    image: "/book-covers/the-berlin-girl.jpg",
    title: "The Berlin girl",
    author: "Robotham, Mandy",
    mediaType: "book",
    holds: 0,
    copies: 12,
    dateAdded: "2020-11-26",
  },
]